fastlane_version "2.171.0"

lane :test do |options|
  if options[:configuration]
    configuration = options[:configuration]
  else
    configuration = "Release"
  end

  scan(configuration: configuration)
  pod_lib_lint(quick: true)
end

