fastlane_version "2.171.0"

lane :test do |options|
  if options[:configuration]
    configuration = options[:configuration]
  else
    configuration = "Release"
  end

  scan(configuration: configuration, xcargs: "OBJROOT=build GCC_GENERATE_TEST_COVERAGE_FILES=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES")
end

