name: "RequestKit CI"

on: 
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - '*'

jobs:
  macOS:
    name: Test macOS
    runs-on: macOS-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_12.3.app/Contents/Developer
    strategy:
      matrix:
        include:
          - lane: test
            env: osx
          - lane: test
            env: ios
          - lane: test
            env: tvos
    steps:
      - uses: actions/checkout@v2
      - name: install
        run: |
          gem install bundler
          bundle install
      - name: Restore cached CocoaPod Spec Repos
        uses: actions/cache@v2
        env:
          cache-name: cache-cocoapods-spec-repos
        with:
          path: ~/.cocoapods/repos
          key: ${{ env.cache-name }}-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: ${{ env.cache-name }}-
      - name: test
        run: |
          set -o pipefail
          bundle exec fastlane ${{ matrix.lane }} --env ${{ matrix.env }}
  spm:
    name: Test with SPM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: sersoft-gmbh/SwiftyActions@v1
        with:
          release-version: 5.3.2
      - name: SPM Test
        run: swift test
